### PR TITLE
Merge Amy's Changes

### PR DESCRIPTION
**Pull request by amyheather**

### CODE REVIEW

**Comment by amyheather** [comment]
Hi @DKBurns , just a few comments and suggestions to support the pull request:

**Branch:** If you want to pull this into a development branch first rather than main, there is an "edit" button on the top right by the pull request - when clicked, it allows you to change the destination from NICE-model-repo:main to a different branch.

**Documentation:** The documentation is hosted via GitHub pages and this is done automatically using GitHub actions. See `.github/workflows/quarto_publish.yaml` - this updates the site with any push to main. There is also a manual trigger button, thanks to the `workflow_dispatch` command. This should work automatically and create a new site linked to your repository.

**Web app:** The application is hosted using shinyapps.io. This is not done via actions, so you have to run commands from local console if you want to create and update the site. This uses the package `rsconnect` (which will be in the renv). Follow these instructions to release the shiny app from your account: <https://shiny.posit.co/r/articles/share/shinyapps/>

**Changes to make:** Currently the links and citations are specific to our repository - you'll want to update these. I've noted all those I could find from searching `pythonhealthdatascience` or `amyheather.shinyapps` in the files:

* `CITATION.cff`: link to GitHub repository
* `README.md`: PenTAG image link, GitHub release badge link, GitHub release data badge link, GitHub last commit link, MIT licence link, link to documentation and web app, website and web app preview image links, links in "GitHub actions" section, citations provided (to GitHub and Zenodo)
* `docs/_quarto.yml`: links to GitHub repository
* `docs/index.qmd`: links to web app and GitHub repository
* `docs/README.md`: links to web app and GitHub repository
* `docs/pages/citation.qmd`: citations provided (to GitHub and Zenodo)
* `shinyapp/txt/intro.md`: links to web app and GitHub repository

**Comment by DKBurns** [comment]
Thanks so much for this, I will review and make the above requested amendments before merging 😃

**Comment by DKBurns** [comment]
I have moved to a `dev` branch as suggested. Good idea, thank you.

**Comment by DKBurns** [comment]
I have merged this into a `dev` branch ready to QC before merging the dev branch into main

**Comment by DKBurns** [comment]
Opening a separate PR into main

**Comment by DKBurns** [comment]
@amyheather could you please provide a link to the online webapp?

EDIT: I think it's here: https://amyheather.shinyapps.io/shinyapp/

**Comment by DKBurns** [comment]
@amyheather 

> CITATION.cff: link to GitHub repository

I do not know what this means. Do you mean the lines

```yaml
repository-code: 'https://github.com/nice-digital/NICE-model-repo'
repository: 'https://github.com/pythonhealthdatascience/NICE-model-repo'
```
on 126 and 127 of `citation.cff`? What am I supposed to do to it? which one do I change? why?


README.md: PenTAG image link, GitHub release badge link, GitHub release data badge link, GitHub last 
commit link, MIT licence link, link to documentation and web app, website and web app preview image 

- image link: is this the link on line 5 of the readme? I do not know how to resolve this as I do not know where the image would otherwise be hosted as I do not control such things.
- badge links: lines 19-26? Same problem as above. Do you have any recommendations which might help?
- last commit: I will need help to do this.
- Documentation and web app: need help with this as well.
- website and preview: same as above

links, links in "GitHub actions" section, citations provided (to GitHub and Zenodo)


docs/_quarto.yml: links to GitHub repository
docs/index.qmd: links to web app and GitHub repository
docs/README.md: links to web app and GitHub repository
docs/pages/citation.qmd: citations provided (to GitHub and Zenodo)
shinyapp/txt/intro.md: links to web app and GitHub repository


All of the above I am unable to resolve. Please could you get in touch with the PenTag and NICE teams to resolve where to host them.

**Comment by amyheather** [comment]
@DKBurns @TomMonks

Hello Darren,

Thanks for your query. I've tried to address and provide some more context around the link queries below. I understand from this and the [message on your other commit](https://github.com/nice-digital/NICE-model-repo/pull/4) that you would like to confirm with PenTAG and NICE where these are hosted. I don't have any contact details that I know of, beyond you and Dawn, but I can forward the query in our email chain there, if you confirm this still remains uncertain/unclear after this response below? Thanks.

However, just to confirm, if you did leave links as they are currently, it will still all work as expected - it would just take you to our hosted versions of the website and app and images.

**Hosting the documentation:** The documentation is hosted via a GitHub action from the repository, on GitHub pages. This is free and public and easy to use, and should be able to happen pretty "automatically" once the commits are merged into main, as far as I am aware.

**Shiny app:** Yes, that is the correct link, when hosted from my account. You can leave it pointing to that app if you wish. However, if you wish to host it yourself, yourself or someone at PenTAG or NICE would need to do so from your own shiny account, following [these instructions](https://shiny.posit.co/r/articles/share/shinyapps/). Shinyapps is again a free to use public service, and requires creating a specific user account to host.

**Citation.CFF:** This file provides instructions on how to cite your repository. You can just remove the pythonhealthdatascience line.

**README links:** Assuming no changes to your repository structure from ours, all items like images and links (except the app) would be in the same folders and locations, and so you should be able to just change out the name in the URL from pythonhealthdatascience starseomrcc to nice-digital nice-model-repo, and this would link to the right places. This includes, if you use the provided GitHub action to host your documentation via GitHub pages, it will follow the same sort of format, and so you can just sub in your org/repo name instead of ours. If you are not going to use that action, and won't be hosting the documentation, then leave all links pointing to mine.

RE: citations -

* Change to your GitHub account.
* If you don't choose to archive on Zenodo, then just remove that.

**Comment by TomMonks** [comment]
@DKBurns @amyheather would it help to arrange a call to go through these points. that might help resolve them quicker?

Cheers

T

**Comment by DKBurns** [comment]
Thanks for getting back on these points, both - I'm sure it can be resolved quickly 😃

**Pull request merged**
