### PR TITLE
STARS project - Merging in changes from Amy Heather

### PR DESCRIPTION
**Pull request by DKBurns**
Amy Heather from Exeter university has made several contributions to materials supporting the open-source model associated with the NICE PATT pilot study.

This pull request proposed to merge in the additions that Amy has made. Amy submitted a pull request previously as #2 . Please refer to #2 for more detail on what was done. The base of this was changed to this branch (`dev`), and after resolving 3 merge conflicts merged. 

This dev branch (and pull request) is specifically for confirming that the model still works correctly, and no errors have been introduced or issues have arisen during the aforementioned merge.

As far as I am aware, there is only one material change to the model code, which does not affect the results. This is to change one line in the model script corresponding to the number of CPU cores the model will use.

Another structural change is to force the code to use a package called `renv`, which saves specific versions of R and packages such that any breaking changes to those packages cannot affect the functionality of this repository.

Please note that the model uses a lot of RAM, so multi-core operations need more. On my computer, the model runs in 9 minutes when using 4 cores. This is due to 32GB of good quality RAM and a mid-tier CPU for a desktop computer, ~16-24GB of which is used by the model.

### CODE REVIEW

**Comment by DKBurns** [comment]
@amyheather I have put several comments and requests for help in #2 and will use `dev` as the basis for the merge into main. Thanks.

In short - I do not know how to get these images and links updated because I do not know where they will be hosted. Please get in touch with @mperrett and @DawnLeeHE to arrange the locations for all the links and where that data will be permanently stored. Until that point I cannot continue.

**Comment by DawnLeeHE** [comment]
Hi all

I'm probably being thick but can we not put the images into a folder on the repo?

If that's not possible we can pop them on the PenTAG server perhaps?



Dawn Lee
Associate Professor of Health Economics and Health Policy
University of Exeter / PenTAG
www.exeter.ac.uk


[http://www.exeter.ac.uk/codebox/email-sig/staff-sig.gif]

This email and any attachment may contain information that is confidential, privileged, or subject to copyright, and which may be exempt from disclosure under applicable legislation. It is intended for the addressee only. If you received this message in error, please let me know and delete the email and any attachments immediately. The University will not accept responsibility for the accuracy/completeness of this email and its attachments.



________________________________

**Comment by amyheather** [comment]
Hello @DawnLeeHE,

Yes - they are all in the repository - I had just used permalinks to refer to them (URL pointing to location in repo) - so options are either (a) changing those to relative file paths, or (b) changing the URLs to point to your repository.

BTW. Have arranged meeting with Darren this afternoon to chat through these uncertainties and get it all sorted. :smile: 

Amy

**Comment by amyheather** [comment]
BTW. Ahead of meeting, have created a pull request to the dev branch, implementing the suggested changes that I was able to implement (e.g. text changes, links): <https://github.com/nice-digital/NICE-model-repo/pull/5>.

**Pull request merged**
